### ISSUE TITLE
Test three-day notification

### ISSUE THREAD

**Issue by typomc** [Lenguita-AI/github-action-due-date-notifications-via-comments#1]
Use this issue to test the three-day notification currently set in `.github/workflows/due-date-notifications-via-comments.yml`.
Due: 2024-06-18

**Comment by typomc** [comment]
This issue is due in 3 day(s).

**Comment by typomc** [comment]
This issue is due in 3 day(s).

**Comment by typomc** [comment]
This issue is due in 2 day(s) on 2024-06-18.

**Comment by typomc** [comment]
This issue is due in 2 day(s) on 2024-06-18.

**Comment by LenguitaAI** [comment]
This issue is due in 2 day(s) on 2024-06-18.

**Comment by LenguitaAI** [comment]
This issue is due in 2 day(s) on 2024-06-18.

**Comment by typomc** [comment]
Test passed.
