### ISSUE TITLE
Bug: Negative Dates in Comments

### ISSUE THREAD

**Issue by typomc** [Lenguita-AI/github-action-due-date-notifications-via-comments#2]
**Description:**
Currently, the system posts comments with negative dates when the due date has passed. This results in incorrect and confusing messages. The following part of the code needs to be adjusted:

```javascript
          if (dueDate <= notificationDate) {
            octokit.rest.issues.createComment({
              owner,
              repo,
              issue_number: issue.number,
              body: `This issue is due in ${daysUntilDue} day(s) on ${dueDateStr}.`
            }).catch(error => core.setFailed(error.message));
          }
        }
      });
    }).catch(error => core.setFailed(error.message));
  } catch (error) {
    core.setFailed(error.message);
  }
}
```

**Proposed Solution:**
We need to handle different cases for the due date to ensure accurate comments. The logic should be updated as follows (pseudo code):

```javascript
if (dueDate < -2) {
  // PASS: No comment should be made if the due date was more than 2 days ago
}

if (dueDate == -1) {
  // The issue due date has passed
  body: `The due date of this issue has **passed**.`
}

if (dueDate == 0) {
  // The issue is due today
  body: `This issue is due **today**.`
}

if (dueDate <= notificationDate) {
  // The issue is due within the notification window
  body: `This issue is due in ${daysUntilDue} day(s) on ${dueDateStr}.`
}
```

**Steps to Reproduce:**
1. Create an issue with a due date in the past.
2. Trigger the notification system.
3. Observe the comment with a negative date.

**Expected Behavior:**
- No comment for due dates more than 2 days in the past.
- Specific comments for due dates that have passed or are due today.
- Correct comments for due dates within the notification window.

Due: 2024-06-18

**Comment by LenguitaAI** [comment]
This issue is due in 1 day(s) on 2024-06-18.

**Comment by LenguitaAI** [comment]
This issue is due in 0 day(s) on 2024-06-18.
