### ISSUE TITLE
Bug: Null Body Error

### ISSUE THREAD

**Issue by typomc** [Lenguita-AI/github-action-due-date-notifications-via-comments#3]
**Description:**
The code encounters an error when attempting to read properties of `null` due to issues without a body or due dates. This results in the following error message:

```
Error: Cannot read properties of null (reading 'match')
```

**Problematic Code Section:**
```javascript
issues.forEach(issue => {
  const dueDateMatch = issue.body.match(/Due\s*[:|-]?\s*(\d{4}-\d{2}-\d{2})/i);
  if (dueDateMatch) {
    const dueDateStr = dueDateMatch[1];
    const dueDate = new Date(dueDateStr);

    // Calculate the difference between today and the due date in days
    const timeDiff = dueDate.getTime() - today.getTime();
    const daysUntilDue = Math.ceil(timeDiff / (1000 * 3600 * 24)); // Convert milliseconds to days

    if (dueDate <= notificationDate) {
      octokit.rest.issues.createComment({
        owner,
        repo,
        issue_number: issue.number,
        body: `This issue is due in ${daysUntilDue} day(s) on ${dueDateStr}.`
      }).catch(error => core.setFailed(error.message));
    }
  }
});
```

**Proposed Solution:**
Add checks to ensure `issue.body` is not `null` and that `dueDateMatch` is not `null` before accessing properties or creating comments.

**Steps to Reproduce:**
1. Create an issue without a body or due date.
2. Trigger the notification system.
3. Observe the error message.

**Expected Behavior:**
- The system should handle issues without a body or due date gracefully, without throwing errors.

**Due: 2024-06-16**

**Comment by LenguitaAI** [comment]
This issue is due in 1 day(s) on 2024-06-18.

**Comment by LenguitaAI** [comment]
This issue is due in 0 day(s) on 2024-06-18.

**Comment by LenguitaAI** [comment]
This issue is due in 0 day(s) on 2024-06-18.

**Comment by LenguitaAI** [comment]
This issue is due in -1 day(s) on 2024-06-17.

**Comment by LenguitaAI** [comment]
This issue is due in -2 day(s), on 2024-06-16.

**Comment by LenguitaAI** [comment]
The due date of this issue has **passed**.

**Comment by LenguitaAI** [comment]
The due date of this issue is **today**.

**Comment by LenguitaAI** [comment]
This issue is due in 1 day(s), on 2024-06-19.

**Comment by LenguitaAI** [comment]
The due date of this issue has **passed**.

**Comment by typomc** [comment]
Added #4 
Fixed.
